# Generated by Django 3.2.11 on 2022-01-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='news_title',
        ),
    ]
