# Generated by Django 3.2.11 on 2022-01-18 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('news', '0003_newspost_news_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='image',
        ),
        migrations.AddField(
            model_name='newspost',
            name='news_image',
            field=models.ForeignKey(help_text='This is the thumbnail for the news article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
